name: nlp-research-template
channels:
  - conda-forge
  - nvidia # nvidia channel for cuda packages
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.10 # or don't specify the version and use latest stable
  - pytorch::pytorch>=2.0 # or don't specify the version and use latest stable
  # CUDA only on linux and windows
  - pytorch::pytorch-cuda=11.8 # [linux]
  - pytorch::pytorch-cuda=11.8 # [win]
  - dargparser
  - wandb
  - lightning
  - transformers=4.36.2
  - tokenizers
  - datasets=2.14.6
  - loguru
  - tqdm
  - accelerate=0.21.0
  - evaluate

  # Dev dependencies
  - black
  - isort
  - flake8

  # pip dependencies
  - pip
  - pip:
      - warmup-scheduler

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
  # - osx-arm64 # This is for M1/M2 MacBooks
  # - linux-aarch64 # This is linux-arm64. We can build Docker images for M1/M2 Macs on top of this - won't support MPS though
  - win-64
